from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TaskAdapter(Protocol):
    """Governed task profile that plugs into the existing orchestrator loop."""

    @property
    def task_id(self) -> str: ...

    def propose(self, cfg: Any) -> dict[str, Any]: ...

    def select_dataset(self, cfg: Any) -> dict[str, Any]: ...

    def run_teacher(self, cfg: Any, proposal: dict[str, Any]) -> dict[str, Any]: ...

    def train_student(
        self, cfg: Any, dataset: dict[str, Any], *, dry_run: bool
    ) -> dict[str, Any]: ...

    def evaluate(self, cfg: Any, train_result: dict[str, Any]) -> dict[str, Any]: ...

    def trust_metrics(self, cfg: Any, eval_result: dict[str, Any]) -> dict[str, Any]: ...

    def hard_fail_check(self, metrics: dict[str, Any]) -> list[str]: ...

    def release_artifact(self, cfg: Any, outcome: dict[str, Any]) -> dict[str, Any] | None: ...

    def rollback_target(self, cfg: Any) -> str | None: ...
